/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClassLevel = bigint;
export interface Note {
  'topic' : string,
  'content' : string,
  'subject' : string,
  'classLevel' : ClassLevel,
}
export interface _SERVICE {
  'addNote' : ActorMethod<[ClassLevel, string, string, string], bigint>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getNote' : ActorMethod<[bigint], [] | [Note]>,
  'getNotesByClass' : ActorMethod<[ClassLevel], Array<Note>>,
  'getNotesBySubject' : ActorMethod<[string], Array<Note>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];