/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassLevel = IDL.Nat;
export const Note = IDL.Record({
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'classLevel' : ClassLevel,
});

export const idlService = IDL.Service({
  'addNote' : IDL.Func(
      [ClassLevel, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getNotesByClass' : IDL.Func([ClassLevel], [IDL.Vec(Note)], ['query']),
  'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassLevel = IDL.Nat;
  const Note = IDL.Record({
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'classLevel' : ClassLevel,
  });
  
  return IDL.Service({
    'addNote' : IDL.Func(
        [ClassLevel, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getNotesByClass' : IDL.Func([ClassLevel], [IDL.Vec(Note)], ['query']),
    'getNotesBySubject' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };