/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScienceNote = IDL.Record({
  'importantPoints' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'chapterTitle' : IDL.Text,
  'definitions' : IDL.Vec(IDL.Text),
  'examples' : IDL.Vec(IDL.Text),
});
export const GameState = IDL.Record({
  'score' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'timeTaken' : IDL.Int,
  'unlockedPuzzles' : IDL.Vec(IDL.Text),
});
export const HighScore = IDL.Record({
  'player' : IDL.Text,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'timeTaken' : IDL.Int,
});

export const idlService = IDL.Service({
  'completeLevel' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'getAllChapters' : IDL.Func([], [IDL.Vec(ScienceNote)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ScienceNote)], ['query']),
  'getPlayerGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getPlayerHighScores' : IDL.Func([IDL.Text], [IDL.Vec(HighScore)], ['query']),
  'initializeChapters' : IDL.Func([], [], []),
  'startTimer' : IDL.Func([], [IDL.Int], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScienceNote = IDL.Record({
    'importantPoints' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'chapterTitle' : IDL.Text,
    'definitions' : IDL.Vec(IDL.Text),
    'examples' : IDL.Vec(IDL.Text),
  });
  const GameState = IDL.Record({
    'score' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'timeTaken' : IDL.Int,
    'unlockedPuzzles' : IDL.Vec(IDL.Text),
  });
  const HighScore = IDL.Record({
    'player' : IDL.Text,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'timeTaken' : IDL.Int,
  });
  
  return IDL.Service({
    'completeLevel' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAllChapters' : IDL.Func([], [IDL.Vec(ScienceNote)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ScienceNote)], ['query']),
    'getPlayerGameState' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GameState)],
        ['query'],
      ),
    'getPlayerHighScores' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HighScore)],
        ['query'],
      ),
    'initializeChapters' : IDL.Func([], [], []),
    'startTimer' : IDL.Func([], [IDL.Int], []),
  });
};

export const init = ({ IDL }) => { return []; };