/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameType = IDL.Variant({
  'sequenceMemory' : IDL.Null,
  'slidingPuzzle' : IDL.Null,
  'stroopEffect' : IDL.Null,
  'patternMemory' : IDL.Null,
  'cardMatching' : IDL.Null,
  'memoryTest' : IDL.Null,
});
export const ScienceNote = IDL.Record({
  'importantPoints' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'chapterNumber' : IDL.Nat,
  'chapterTitle' : IDL.Text,
  'definitions' : IDL.Vec(IDL.Text),
  'examples' : IDL.Vec(IDL.Text),
});
export const AnalyticsView = IDL.Record({
  'gamePlayCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalVisitors' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const MemoryTestHighScore = IDL.Record({
  'streak' : IDL.Nat,
  'player' : IDL.Text,
  'date' : IDL.Int,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'timeTaken' : IDL.Int,
});
export const MemoryTestState = IDL.Record({
  'streak' : IDL.Nat,
  'hintsRemaining' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'gameOver' : IDL.Bool,
  'currentLevel' : IDL.Nat,
  'timeTaken' : IDL.Int,
});
export const GameState = IDL.Record({
  'memoryTestRecords' : IDL.Opt(IDL.Vec(MemoryTestHighScore)),
  'score' : IDL.Nat,
  'memoryTestState' : IDL.Opt(MemoryTestState),
  'gameType' : GameType,
  'currentLevel' : IDL.Nat,
  'timeTaken' : IDL.Int,
  'unlockedPuzzles' : IDL.Vec(IDL.Text),
});
export const HighScore = IDL.Record({
  'player' : IDL.Text,
  'level' : IDL.Nat,
  'score' : IDL.Nat,
  'gameType' : GameType,
  'timeTaken' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeLevel' : IDL.Func(
      [IDL.Text, GameType, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'completeMemoryTest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'getAllChapters' : IDL.Func([], [IDL.Vec(ScienceNote)], ['query']),
  'getAnalytics' : IDL.Func([IDL.Text], [IDL.Opt(AnalyticsView)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ScienceNote)], ['query']),
  'getMemoryTestHighScores' : IDL.Func(
      [],
      [IDL.Vec(MemoryTestHighScore)],
      ['query'],
    ),
  'getPlayerGameState' : IDL.Func([IDL.Text], [IDL.Opt(GameState)], ['query']),
  'getPlayerHighScores' : IDL.Func([IDL.Text], [IDL.Vec(HighScore)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeChapters' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGamePlay' : IDL.Func([IDL.Text], [], []),
  'recordVisit' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTimer' : IDL.Func([], [IDL.Int], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameType = IDL.Variant({
    'sequenceMemory' : IDL.Null,
    'slidingPuzzle' : IDL.Null,
    'stroopEffect' : IDL.Null,
    'patternMemory' : IDL.Null,
    'cardMatching' : IDL.Null,
    'memoryTest' : IDL.Null,
  });
  const ScienceNote = IDL.Record({
    'importantPoints' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'chapterNumber' : IDL.Nat,
    'chapterTitle' : IDL.Text,
    'definitions' : IDL.Vec(IDL.Text),
    'examples' : IDL.Vec(IDL.Text),
  });
  const AnalyticsView = IDL.Record({
    'gamePlayCounts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalVisitors' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const MemoryTestHighScore = IDL.Record({
    'streak' : IDL.Nat,
    'player' : IDL.Text,
    'date' : IDL.Int,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'timeTaken' : IDL.Int,
  });
  const MemoryTestState = IDL.Record({
    'streak' : IDL.Nat,
    'hintsRemaining' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'gameOver' : IDL.Bool,
    'currentLevel' : IDL.Nat,
    'timeTaken' : IDL.Int,
  });
  const GameState = IDL.Record({
    'memoryTestRecords' : IDL.Opt(IDL.Vec(MemoryTestHighScore)),
    'score' : IDL.Nat,
    'memoryTestState' : IDL.Opt(MemoryTestState),
    'gameType' : GameType,
    'currentLevel' : IDL.Nat,
    'timeTaken' : IDL.Int,
    'unlockedPuzzles' : IDL.Vec(IDL.Text),
  });
  const HighScore = IDL.Record({
    'player' : IDL.Text,
    'level' : IDL.Nat,
    'score' : IDL.Nat,
    'gameType' : GameType,
    'timeTaken' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeLevel' : IDL.Func(
        [IDL.Text, GameType, IDL.Nat, IDL.Int, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'completeMemoryTest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'getAllChapters' : IDL.Func([], [IDL.Vec(ScienceNote)], ['query']),
    'getAnalytics' : IDL.Func([IDL.Text], [IDL.Opt(AnalyticsView)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(ScienceNote)], ['query']),
    'getMemoryTestHighScores' : IDL.Func(
        [],
        [IDL.Vec(MemoryTestHighScore)],
        ['query'],
      ),
    'getPlayerGameState' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GameState)],
        ['query'],
      ),
    'getPlayerHighScores' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HighScore)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeChapters' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGamePlay' : IDL.Func([IDL.Text], [], []),
    'recordVisit' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTimer' : IDL.Func([], [IDL.Int], []),
  });
};

export const init = ({ IDL }) => { return []; };