/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsView {
  'gamePlayCounts' : Array<[string, bigint]>,
  'totalVisitors' : bigint,
  'totalSessions' : bigint,
}
export interface GameState {
  'memoryTestRecords' : [] | [Array<MemoryTestHighScore>],
  'score' : bigint,
  'memoryTestState' : [] | [MemoryTestState],
  'gameType' : GameType,
  'currentLevel' : bigint,
  'timeTaken' : bigint,
  'unlockedPuzzles' : Array<string>,
}
export type GameType = { 'sequenceMemory' : null } |
  { 'slidingPuzzle' : null } |
  { 'stroopEffect' : null } |
  { 'patternMemory' : null } |
  { 'cardMatching' : null } |
  { 'memoryTest' : null };
export interface HighScore {
  'player' : string,
  'level' : bigint,
  'score' : bigint,
  'gameType' : GameType,
  'timeTaken' : bigint,
}
export interface MemoryTestHighScore {
  'streak' : bigint,
  'player' : string,
  'date' : bigint,
  'level' : bigint,
  'score' : bigint,
  'correctAnswers' : bigint,
  'timeTaken' : bigint,
}
export interface MemoryTestState {
  'streak' : bigint,
  'hintsRemaining' : bigint,
  'correctAnswers' : bigint,
  'gameOver' : boolean,
  'currentLevel' : bigint,
  'timeTaken' : bigint,
}
export interface ScienceNote {
  'importantPoints' : Array<string>,
  'content' : string,
  'chapterNumber' : bigint,
  'chapterTitle' : string,
  'definitions' : Array<string>,
  'examples' : Array<string>,
}
export interface UserProfile { 'name' : string, 'avatarUrl' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeLevel' : ActorMethod<
    [string, GameType, bigint, bigint, bigint, bigint],
    undefined
  >,
  'completeMemoryTest' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint, bigint],
    boolean
  >,
  'getAllChapters' : ActorMethod<[], Array<ScienceNote>>,
  'getAnalytics' : ActorMethod<[string], [] | [AnalyticsView]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapter' : ActorMethod<[bigint], [] | [ScienceNote]>,
  'getMemoryTestHighScores' : ActorMethod<[], Array<MemoryTestHighScore>>,
  'getPlayerGameState' : ActorMethod<[string], [] | [GameState]>,
  'getPlayerHighScores' : ActorMethod<[string], Array<HighScore>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeChapters' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordGamePlay' : ActorMethod<[string], undefined>,
  'recordVisit' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTimer' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];